### ISSUE TITLE
Need support for [username:password] authentication

### ISSUE THREAD

**Issue by evenmun** [BrobridgeOrg/atomic-jetstream#5]
Hei

We are not able to use this Node with **username:password** enabled in JetStream.

1. When we enable **username:password** in the nats.conf, we get the response:

`"Authorization Violation"`

_This was expected!_

2. Then we add **username:password** to Connection String 

`"nats://username:password@localhost:4222"`

Result:

```
TypeError [ERR_INVALID_URL]: Invalid URL
2024-04-01 13:22:08     at new NodeError (node:internal/errors:387:5)
2024-04-01 13:22:08     at URL.onParseError (node:internal/url:565:9)
2024-04-01 13:22:08     at new URL (node:internal/url:641:5)
2024-04-01 13:22:08     at hostPort (/data/node_modules/nats/lib/nats-base-client/servers.js:86:17)
2024-04-01 13:22:08     at new ServerImpl (/data/node_modules/nats/lib/nats-base-client/servers.js:104:19)
2024-04-01 13:22:08     at /data/node_modules/nats/lib/nats-base-client/servers.js:169:35
2024-04-01 13:22:08     at Array.forEach (<anonymous>)
2024-04-01 13:22:08     at new Servers (/data/node_modules/nats/lib/nats-base-client/servers.js:167:21)
2024-04-01 13:22:08     at new ProtocolHandler (/data/node_modules/nats/lib/nats-base-client/protocol.js:306:24)
2024-04-01 13:22:08     at Function.<anonymous> (/data/node_modules/nats/lib/nats-base-client/protocol.js:562:23) {
2024-04-01 13:22:08   input: 'http://[username:password@localhost:4222]',
2024-04-01 13:22:08   code: 'ERR_INVALID_URL'
2024-04-01 13:22:08 }
```

**Comment by telemac** [comment]
Hello,

I just added a pull request that adds a user/password field to the server parameters to allow to connect to nats with credentials.
